### ISSUE TITLE
Letters look really close together even between words

### ISSUE THREAD

**Issue by katerberg** [ryapric/meowify#1]
<img width="322" alt="Screen Shot 2020-08-05 at 8 06 51 PM" src="https://user-images.githubusercontent.com/479643/89478975-3d5f3e00-d757-11ea-8ccc-2ef07b24581e.png">

It should translate spaces into 2-3 spaces in order to make it clear that words are apart.

**Comment by ryapric** [comment]
This is a lovely request, @katerberg.

The first one is two spaces, the second is three. Which do you like better? I think I'm partial to the latter (three spaces); and four ends up being a bit much.

![2-spaces](https://user-images.githubusercontent.com/22351501/89493474-dbfc9680-d779-11ea-80aa-dc43796db787.png)
![3-spaces](https://user-images.githubusercontent.com/22351501/89493478-de5ef080-d779-11ea-9b59-e5576a9a3b41.png)

**Comment by katerberg** [comment]
Hmmm, 3 looks better most definitely.

**Comment by ryapric** [comment]
Done!
